{{- if .Values.persistence.images.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mediamanager.fullname" . }}-images
  labels:
    {{- include "mediamanager.labels" . | nindent 4 }}
  {{- with .Values.persistence.images.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.images.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.images.size | quote }}
  {{- with .Values.persistence.images.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
